version:  '3'
services:
  datascience-notebook:
      build: .
      volumes:
        - ${LOCAL_WORKING_DIR}:/home/jovyan/work
        - ${LOCAL_DATASETS}:/home/jovyan/work/datasets
        - ${LOCAL_MODULES}:/home/jovyan/work/modules
        - ${LOCAL_SSL_CERTS}:/etc/ssl/notebook
      ports:
        - ${PORT}:8888
      container_name: jupyter_notebook
      environment:
        - JUPYTER_ENABLE_LAB=yes
      command: "start-notebook.sh"
